# -*- coding: utf-8 -*-
"""Task_Management_Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fl0QAzLfnsv7TAYd7t5N8-X6xJyywjew
"""

# Importando a biblioteca math
import math

# Instancias do nosso problema
inf = math.inf

tempos =  [
           [inf, inf, inf, inf, inf, inf, inf],
           [5, inf, 3, 9, 4, 2, 6],
           [3, 3, inf, 6, 2, 3, 5],
           [4, 9, 6, inf, 7, 2, 6],
           [7, 4, 2, 7, inf, 4, 8],
           [2, 2, 3, 3, 4, inf, 1],
           [1, 6, 5, 5, 8, 1, inf]
           ]

n = 7

solve = [0, 2, 3, 1, 5, 6, 4]

# conferindo os dados

print(tempos)
print()
print(solve)

# Vamos implementar o procedimento que calcula o custo
# De acordo com nossa solução e matriz de tempos

def calc_custo(solve, tempos, n):

    custo_total = 0

    for i in range(n - 1):
        tarefa_anterior = solve[i - 1]
        tarefa_atual = solve[i]
        custo_total += tempos[tarefa_anterior][tarefa_atual]

    return custo_total

# Vamos chamar nosso procedimento e exibir o custo total

custo = calc_custo(solve, tempos, n)

# Podemos observar que a solução foi inviável - inf
print(f"Dada a Solução: {solve}")
print()
print(f"O custo total será: {custo}")